config/routes.rb
Rails.application.routes.draw do
  #resources :sessions
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:create, :destroy, :new]

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "users#index"
  get 'categories/index', to: 'categories#index' , as: :category_index
  get 'categories/show', to: 'categories#show'
  get 'categories/new', to: 'categories#new', as: :new_category
  post "categories", to: "categories#create"
  get 'categories/edit', to: 'categories#edit'
  get 'categories/:id/edit', to: "categories#edit", as: :edit_category
  post "categories/:id", to: "categories#update", as: :category
  get 'categories/:id', to: "categories#show"
  delete "categories/:id", to: "categories#delete"

  get "articles/index", to: "articles#index" , as: :article_index
  get "articles/new", to: "articles#new", as: :new_article
  post "articles", to: "articles#create"
  get "articles/:id", to: "articles#show"
  get "articles/:id/edit", to: "articles#edit", as: :edit_article
  post "articles/:id", to: "articles#update", as: :article
  delete "articles/:id", to: "articles#delete"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category, class_name: 'Category', foreign_key: 'category_id'
  has_one_attached :img

  validates :title, presence: true, length: {minimum: 2, maximum: 50}
  validates :img, presence: true
  validates :url, presence: true, length: {minimum: 2, maximum: 100}
  validates :island, presence: true, length: {minimum: 2, maximum: 15}
  validates :category_id, presence: true
  validates :exturl, presence: true, length: {minimum: 2, maximum: 300}
  validates :info, presence: true, length: {minimum: 2, maximum: 1000}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, class_name: 'Article', foreign_key: 'category_id'
  has_one_attached :img

  validates :title, presence: true, length: {minimum: 2, maximum: 20}
  validates :img, presence: true
  validates :url, presence: true, length: {minimum: 2, maximum: 60}
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  PASSWORD_FORMAT = /\A
  (?=.{6,15})          # Must contain 6 or more characters
  (?=.*\d)           # Must contain a digit
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
  (?=.*[[:^alnum:]]) # Must contain a symbol
/x


  validates :email, :username, presence: true, uniqueness: true
  validates :password, presence: true

  validates :email, format: { with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/}
  validates :username, format: { with: /\A([a-zA-Z]+){2,4}\z/}
  validates :password, format: { with: PASSWORD_FORMAT }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_authenticated?
  helper_method :user_not_authenticated?
  helper_method :is_admin?

  def current_user
    User.find session[:user_id] if session[:user_id]
  end

  def user_authenticated?
    !current_user.nil?
  end

  def user_not_authenticated?
    current_user.nil?
  end

  def is_admin?
    user_authenticated? ? current_user.admin : true
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :is_admin?, only: [:show, :index, :new, :create, :update, :delete, :edit]
  @root_url = "/articles/index"
  layout 'application'
  add_flash_types :notice

  def index
    @articles = Article.all()
  end

  def show
    @articles = Article.find(params[:id])
  end

  def new
    @articles = Article.new
  end

  def create
    @articles = Article.create(params_articles)
    if @articles.save
      redirect_to article_index_path
    else
      render 'new'
    end
  end

  def edit
    @articles = Article.find(params[:id])
  end

  def update
    @articles = Article.find(params[:id])
    if @articles.update(params_articles)
      redirect_to article_index_path
    else
      render 'edit'
    end
  end

  def delete
    @articles = Article.find(params[:id])
    @articles.destroy
    redirect_to article_index_path
  end

  def params_articles
    params.require(:article).permit(:title, :img, :url,:island,:exturl,:info,:category_id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :is_admin?, only: [:show, :index, :new, :create, :update, :delete, :edit]
  @root_url = "/categories/index"

  layout 'application'
  add_flash_types :notice

  def index
    @categories = Category.all()
  end

  def show
    @categories = Category.find(params[:id])
  end

  def new
    @categories = Category.new
  end

  def create
    @categories = Category.create(params_categories)
    if @categories.save
      redirect_to category_index_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.find(params[:id])
  end

  def update
    @categories = Category.find(params[:id])
    if @categories.update(params_categories)
      redirect_to category_index_path
    else
      render 'edit'
    end
  end

  def delete
    @categories = Category.find(params[:id])
    @categories.destroy
    redirect_to category_index_path
  end

  def params_categories
    params.require(:category).permit(:title, :img, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :user_not_authenticated?, only: [:create, :new]
  before_action :user_authenticated?, only: [:destroy]


  def new
  end

  def create
    @user = User.find_by email: params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      return redirect_to root_path
    end
    redirect_to login_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :user_not_authenticated?, only: [:new, :create]
  before_action :is_admin?, only: [:show, :index, :create, :update, :destroy, :edit]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "El usuario se ha creado de forma correcta." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "El usuario ha sido actualizado correctamente." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "El usuario ha sido eliminado correctamente" }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :image, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @articles, html: { method: :post} ,local: true) do |form| %>
  <div class="row">
  <% if @articles.errors.any? %>
      <div class="alert-danger">
        <span>
          Se han escontrado
          <%= pluralize(@articles.errors.count, "error") %>:
        </span>
        <ul>
          <% @articles.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if user_authenticated? && is_admin?%>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label "Título" %>
          <%= form.text_field :title, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :url %>
          <%= form.url_field :url, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <label for="island">Isla</label>
        <% islas = ["Tenerife", "Gran Canaria","La Palma","La Gomera","El Hierro","Lanzarote","Fuerteventura","La Graciosa"]; %>
        <select name="article[island]" class="form-control">
          <option value="null">Seleccione isla</option>
          <% islas.each do |c| %>
            <option value="<%= c %>" <%= @articles.island === c ? "selected" : "" %>><%= c %></option>
          <% end %>
        </select>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label "Url Externa" %>
          <%= form.url_field :exturl, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label "Información" %>
          <%= form.text_field :info, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label for="categoria_id">Categoria</label>
          <select name="article[category_id]" class="form-control">
            <option value="null">Seleccione categoría</option>
            <% Category.all.each do |c| %>
              <option value="<%= c.id %>" <%= @articles.category_id === c.id ? "selected" : "" %>><%= c.title %></option>
            <% end %>
          </select>
        </div>
      </div>
      <div class="col-md-12">
        <% if @articles.img.attached? %>
          <%= image_tag @articles.img ,style:"width: 100px;height: auto; margin-top:50px" %>
          <% end %>
            <div class="form-group">
          <%= form.label "Imagen" %>
          <%= form.file_field :img,class:"form-control-file mt-2"  %>
        </div>
      </div>
      <div class="d-flex justify-content-center mb-2 mt-4">
        <%= form.submit "Guardar", class: "btn btn-dark ml-2" %>
        <%= link_to 'Cancelar', :back, class: "btn btn-primary ml-2" %>
      </div>
    <%end %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <% if user_authenticated? && is_admin?%>
            <h1 class="mb-2">Editar artículo</h1>
            <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">

            <div class="col-12">
              <%= render "articles/form" %>
            </div>
          <%else %>
            <h1 class="mb-2">ACCESO RESTRINGIDO</h1>
          <%end %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content py-3 ">
    <% if user_authenticated? && is_admin?%>
      <div class="table-responsive">
        <div class="w-100 text-center">
          <h1>Artículos</h1>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
        </div>
        <div class="text-center align-right">  <%= link_to "Crear artículo", new_article_path, class: "btn btn-info " %></div>
        <table class="table table-striped">
          <thead>

          <tr>
            <th class="text-center">Categoría</th>
            <th class="text-center">Título</th>
            <th class="text-center">Isla</th>
            <th class="text-center" colspan="3">Acciones</th>
          </tr>
          </thead>

          <% @articles.each do |article| %>
            <tbody>
            <tr>
              <td class="text-center align-middle"> <%= Category.find(article.category_id).title %> </td>
              <td class="text-center align-middle"> <%= article.title %> </td>
              <td class="text-center align-middle"> <%= article.island %> </td>
              <td class="text-center align-middle">
                <%= link_to "Detalles",article, class: "btn btn-info " %>
                <%= link_to "Editar", edit_article_path(article.id), class: "btn btn-success ml-2" %>
                <%= link_to "Eliminar", article, method: :delete, class: "btn btn-danger ml-2",
                            data: { confirm: '¿Desea eliminar?'} %>
              </td>
            </tr>

            </tbody>
          <% end %>
        </table>
      </div>
    <%else %>
      <h1 class="mb-2">ACCESO RESTRINGIDO</h1>
    <%end %>
  </div>
</section>

app/views/articles/new.html.erb
<section class="offset-md-2 col-md-8 col-xs-12 custom-form">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-md-10 col-xs-12 py-4">
      <div class="row">
        <div class="col-12 text-center">
          <% if user_authenticated? && is_admin?%>
            <h1 class="mb-2">Crear artículo</h1>
            <hr class="teal accent-3 mb-4 mt-0 mx-auto border-dark" style="width: 200px;">

            <div class="col-12">
              <%= render "articles/form" %>
            </div>
          <%else %>
            <h1 class="mb-2">ACCESO RESTRINGIDO</h1>
          <%end %>

        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/show.html.erb
<section class="offset-md-2 col-md-8 col-xs-12">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-12 py-4">
      <% if user_authenticated? && is_admin?%>
        <div class="w-100 text-center mb-3">
          <h1>Información del artículo</h1>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
        </div>
        <div class="row">
          <div class="col-md-12 text-center">
            <div>
              <p> TITULO: <%= @articles.title %> </p>
            </div>
            <div>
              <p> <%= image_tag url_for(@articles.img), style:"width: 120px;height: auto; margin-top:20px" %> </p>
            </div>
            <div>
              <p> URL: <%= @articles.url %> </p>
            </div>
            <div>
              <p> Isla: <%= @articles.island %> </p>
              <p> Categoría: <%= @articles.category_id %> </p>
              <p> Url externa: <%= @articles.exturl %> </p>
            </div>
            <div>
              <p> Información: <%= @articles.info %> </p>
            </div>
            <div>
              <%= link_to "Editar", edit_article_path(@articles.id), class: "btn btn-success ml-2" %>
              <%= link_to "Eliminar", @articles, method: :delete, class: "btn btn-danger ml-2" %>
            </div>
          </div>
        </div>
      <%else %>
        <h1 class="mb-2">ACCESO RESTRINGIDO</h1>
      <%end %>
    </div>
  </div>
</section>

app/views/categories/_form.html.erb
<%= form_with(model: @categories, html: { method: :post} ,local: true) do |form| %>
  <div class="row">
  <% if @categories.errors.any? %>
      <div class="alert-danger">
        <span>
          Se han escontrado
          <%= pluralize(@categories.errors.count, "error") %>:
        </span>
        <ul>
          <% @categories.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if user_authenticated? && is_admin?%>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label "Título" %>
          <%= form.text_field :title, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :url %>
          <%= form.url_field :url, class:"form-control" %>
        </div>
      </div>
      <div class="col-md-12">
        <% if @categories.img.attached? %>
          <%= image_tag @categories.img ,style:"width: 100px;height: auto; margin-top:50px" %>
          <% end %>
            <div class="form-group">
          <%= form.label "Imagen" %>
          <%= form.file_field :img,class:"form-control-file mt-2"  %>
        </div>
      </div>
    <div class="d-flex justify-content-center mb-2 mt-4">
      <%= form.submit "Guardar", class: "btn btn-dark ml-2" %>
      <%= link_to 'Cancelar', :back, class: "btn btn-primary ml-2" %>
    </div>
      </div>
  <%end%>
<% end %>

<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content py-3 ">

    <div class="table-responsive">
      <div class="w-100 text-center">
        <h1>Artículos</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>
      <div class="text-center align-right">  <%= link_to "Crear artículo", new_article_path, class: "btn btn-info " %></div>
      <table class="table table-striped">
        <thead>

        <tr>
          <th class="text-center">Categoría</th>
          <th class="text-center">Título</th>
          <th class="text-center">Isla</th>
          <th class="text-center" colspan="3">Acciones</th>
        </tr>
        </thead>

        <% Article.all.each do |article| %>
          <tbody>
          <% if article.category_id=== @categories.id %>
            <tr>
              <td class="text-center align-middle"> <%= Category.find(article.category_id).title %> </td>
              <td class="text-center align-middle"> <%= article.title %> </td>
              <td class="text-center align-middle"> <%= article.island %> </td>
              <td class="text-center align-middle">
                <%= link_to "Detalles",article, class: "btn btn-info ml-2 mt-1 " %>
                <%= link_to "Editar", edit_article_path(article.id), class: "btn btn-success ml-2 mt-1" %>
                <%= link_to "Eliminar", article, method: :delete, class: "btn btn-danger ml-2 mt-1",
                            data: { confirm: '¿Desea eliminar?'} %>
              </td>
            </tr>
          <% end %>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</section>

app/views/categories/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content py-3 ">
    <% if user_authenticated? && is_admin?%>
      <div class="table-responsive">
        <div class="w-100 text-center">
          <h1>Categorias</h1>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
        </div>
          <div class="text-center align-right">  <%= link_to "Crear categoria", new_category_path, class: "btn btn-info " %></div>
        <table class="table table-striped">
          <thead>

          <tr>
            <th class="text-center">Título</th>
            <th class="text-center" colspan="3">Acciones</th>
          </tr>
          </thead>

          <% @categories.each do |categoria| %>
            <tbody>
            <tr>
              <td class="text-center align-middle"> <%= categoria.title %> </td>
              <td class="text-center align-middle">
                <%= link_to "Detalles",categoria, class: "btn btn-info " %>
                <%= link_to "Editar", edit_category_path(categoria.id), class: "btn btn-success ml-2" %>
                <%= link_to "Eliminar", categoria, method: :delete, class: "btn btn-danger ml-2",
                            data: { confirm: '¿Desea eliminar?'} %>
              </td>
            </tr>

            </tbody>
          <% end %>
        </table>
      </div>
      <%else %>
        <h1 class="mb-2">ACCESO RESTRINGIDO</h1>
      <%end %>
  </div>
</section>

app/views/categories/show.html.erb
<section class="offset-md-2 col-md-8 col-xs-12">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-12 py-4">
      <% if user_authenticated? && is_admin?%>
        <div class="w-100 text-center mb-3">
          <h1>Información de la categoría</h1>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
        </div>

        <div class="row">
          <div class="col-md-12 text-center">
            <div>
              <p> TITULO: <%= @categories.title %> </p>
            </div>
            <div>
              <p> <%= image_tag url_for(@categories.img), style:"width: 120px;height: auto; margin-top:20px" %> </p>
            </div>
            <div>
              <p> URL: <%= @categories.url %> </p>
            </div>
            <div>
              <%= link_to "Editar", edit_category_path(@categories.id), class: "btn btn-success ml-2" %>
              <%= link_to "Eliminar", @categories, method: :delete, class: "btn btn-danger ml-2" %>
            </div>
          </div>
        </div>
      <%else %>
        <h1 class="mb-2">ACCESO RESTRINGIDO</h1>
      <%end %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Somos8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class="offset-md-1 col-md-10 col-xs-12">

    <div class="d-flex flex-wrap align-items-center">
      <a class="mx-3" href="#">
        <h1 id="Titulo" class="text-dark">
          Somos8
        </h1>
        <h5>
          <%if current_user %>
            Bienvenido/a <%= current_user.username %>
          <%end %>
        </h5>
      </a>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light bg-light mt-2">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_authenticated? && is_admin? %>
                <li class="nav-item">
                  <%= link_to "Categorías", category_index_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Artículos", article_index_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Usuarios", users_path, class: "nav-link" %>
                </li>
          <%end %>
          <% if !user_authenticated? %>
              <li class="nav-item">
                <%= link_to "Iniciar sesión", login_path, class: "nav-link" %>
              </li>
          <%else %>
              <%= link_to "Cerrar sesión", logout_path, method: :post, class: "nav-link" %>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>

  <body>
    <% if notice %>
      <p class="notice alert-primary"><%= notice %></p>
    <%end%>
    <% if alert%>
      <p class="alert alert-danger"><%= alert %></p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="alert-danger text-end">
      <div class="text-start">
        Se han encontrado
        <%= pluralize(@user.errors.count, "error") %>:
      </div>
      <div class="text-start">
        <ul>
          <% @user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>

    </div>
  <% end %>
  </div>
  <div class="col-12 text-center">
      <div class="row">
        <div class="form-group mb-4">
          <div class="form-group mb-4">
            <%= form.label :username %>
            <%= form.text_field :username %>
          </div>
          <div class="form-group mb-4">
            <%= form.label :email %>
            <%= form.text_field :email %>
          </div>
          <div class="form-group mb-4">
            <%= form.label :password %>
            <%= form.password_field :password %>
          </div>
          <div class="form-group mb-4">
            <%= form.label :admin %>
            <%= form.text_field :admin %>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-center mb-2 mt-4">
        <%= form.submit "Guardar", class: "btn btn-dark" %>
        <%= link_to 'Cancelar', users_path, class: "btn btn-primary ml-2" %>
      </div>
  </div>
<% end %>

app/views/users/index.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content py-3 ">
        <% if user_authenticated? && is_admin?%>
          <div class="table-responsive">
            <div class="w-100 text-center">
              <h1>Usuarios</h1>
              <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-autschema_migrationso border-dark" style="width: 200px;">
            </div>
            <div class="text-center align-right"> <%= link_to 'Nuevo Usuario', new_user_path, class: "btn btn-info"%></div>

            <table class="table table-striped">
              <thead>
              <tr>
                <th>Nombre de usuario</th>
                <th>Correo electrónico</th>
                <th>Contraseña</th>
                <th>Admin</th>

                <th colspan="3"></th>
              </tr>
              </thead>

              <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.username %></td>
                  <td><%= user.email %></td>
                  <td><%= user.password %></td>
                  <td><%= user.admin %></td>
                  <td><%= link_to 'Detalles', user, class: "btn btn-info" %></td>
                  <td><%= link_to 'Editar', edit_user_path(user), class: "btn btn-success ml-2" %></td>
                  <td><%= link_to 'Eliminar', user, method: :delete, class: "btn btn-danger ml-2", data: { confirm: '¿Desea eliminar?' } %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        <%else %>>
          <div class="w-100 text-center">
            <h1 class="mb-2">ACCESO RESTRINGIDO</h1>
          </div>
        <%end %>
  </div>
</section>

app/views/users/show.html.erb
<section class="offset-md-2 col-md-8 col-xs-12">
  <div class="d-flex justify-content-center mt-5 content">
    <div class="col-12 py-4">
      <% if user_authenticated? && is_admin? %>
        <div class="w-100 text-center mb-3">
          <h1>Información del usuario</h1>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
        </div>
        <div class="row">
          <div class="col-md-12 text-center">
            <div>
              <p><strong>NOMBRE DE USUARIO: </strong><%= @user.username %></p>
            </div>
            <div>
              <p><strong>CORREO ELECTRÓNICO: </strong> <%= @user.email %></p>
            </div>
            <div>
              <p><strong>CONTRASEÑA: </strong> <%= @user.password %></p>
            </div>
            <div>
              <p><strong>ADMIN: </strong> <%= @user.admin %></p>
            </div>
          </div>
        </div>
        <div>
          <%= link_to "Editar", edit_user_path(@user.id), class: "btn btn-success" %>
          <%= link_to "Eliminar", @user, method: :delete, class: "btn btn-danger" %>
          <%= link_to 'Volver', users_path, class: "btn btn-primary ml-2" %>
        </div>
      </div>
      <%else %>
        <h1 class="mb-2">ACCESO RESTRINGIDO</h1>
      <%end %>
  </div>
</section>